AllPersonalities = [
    "brave", # 勇敢
    "shy", # 害羞
    "friendly", # 友善
    "greedy", # 貪婪
    "wise", # 智慧
    "loyal", # 忠誠
    "curious", # 好奇
    "lazy", # 懶惰
    "materialistic", # 物質主義
    "optimistic", # 樂觀
    "pessimistic", # 悲觀
    "sarcastic", # 諷刺
    "romantic", # 浪漫
    "cautious", # 謹慎
    "ambitious", # 有野心
    "stubborn", # 固執
    "generous", # 慷慨
    "jealous", # 嫉妒
    "cheerful", # 開朗
    "timid", # 膽小
    "diligent", # 勤奮
    "arrogant", # 傲慢
    "humble", # 謙虛
    "forgiving", # 寬容
    "vengeful", # 復仇
    "pragmatic", # 實際
    "dreamy", # 愛幻想
    "protective", # 保護他人
    "adventurous", # 愛冒險
    "calculating", # 精於算計
    "compassionate", # 有同情心
    "eccentric", # 古怪
    "strict", # 嚴格
    "playful", # 愛玩
    "reserved", # 內向
    "outgoing", # 外向
    "moody", # 情緒化
    "decisive", # 果斷
    "indecisive", # 優柔寡斷
    "meticulous", # 細心
    "reckless", # 魯莽
    "tactful", # 圓滑
    "blunt", # 直率
    "patient", # 有耐心
    "impatient", # 沒耐心
    "faithful", # 忠實
    "skeptical", # 懷疑
    "authoritative", # 權威
    "submissive", # 順從
    "innovative", # 創新
]