AllRoles = [
    "farmer", # 農夫
    "blacksmith", # 鐵匠
    "merchant", # 商人
    "guard", # 守衛
    "priest", # 牧師
    "innkeeper", # 旅館老闆
    "hunter", # 獵人
    "fisherman", # 漁夫
    "herbalist", # 草藥師
    "scholar", # 學者
    "king", # 國王（唯一）
    "queen", # 王后（唯一）
    "bard", # 吟遊詩人
    "thief", # 盜賊
    "knight", # 騎士
    "cook", # 廚師
    "tailor", # 裁縫
    "miner", # 礦工
    "carpenter", # 木匠
    "alchemist", # 煉金術士
    "apprentice", # 學徒
    "beggar", # 乞丐
    "noble", # 貴族
    "servant", # 僕人
    "sailor", # 水手
    "witch", # 女巫
    "healer", # 治療師
    "stable master", # 馬廄主人
    "fool",  # 小丑
    "messenger", # 信使
]