role_with_request_nouns = {
    "farmer": ["crop", "field", "seed", "harvest", "vegetable", "plow", "barn", "soil"],
    "blacksmith": ["weapon", "anvil", "armor", "hammer", "forge", "metal", "tool", "shield"],
    "merchant": ["goods", "market", "coin", "spice", "caravan", "permit", "trade", "stall"],
    "guard": ["gate", "law", "shield", "patrol", "bodyguard", "prisoner", "crime", "witness"],
    "priest": ["blessing", "altar", "faith", "ceremony", "prayer", "donation", "wedding", "festival"],
    "innkeeper": ["room", "feast", "banquet", "guest", "drink", "parade", "music", "meal"],
    "hunter": ["bow", "trap", "animal", "forest", "prey", "camp", "fur", "arrow"],
    "fisherman": ["fish", "net", "boat", "river", "sea", "bait", "rod", "catch"],
    "herbalist": ["herb", "remedy", "plant", "potion", "flower", "balm", "tincture", "root"],
    "scholar": ["book", "scroll", "knowledge", "study", "manuscript", "library", "debate", "research"],
    "king": ["crown", "throne", "law", "treasure", "festival", "decree", "court", "kingdom"],
    "queen": ["crown", "jewel", "parade", "masquerade", "wedding", "garden", "court", "blessing"],
    "bard": ["song", "music", "story", "poetry", "instrument", "dance", "lyre", "performance"],
    "thief": ["lock", "mask", "secret", "disguise", "loot", "hideout", "crime", "escape"],
    "knight": ["armor", "shield", "horse", "joust", "banner", "tournament", "sword", "duty"],
    "cook": ["recipe", "kitchen", "ingredient", "bread", "meal", "dessert", "oven", "feast"],
    "tailor": ["outfit", "fabric", "thread", "cloak", "hat", "needle", "fashion", "pattern"],
    "miner": ["ore", "gem", "pickaxe", "helmet", "cart", "stone", "tunnel", "mine"],
    "carpenter": ["wood", "tool", "furniture", "house", "plank", "nail", "workbench", "beam"],
    "alchemist": ["potion", "elixir", "ingredient", "remedy", "tincture", "flask", "crystal", "formula"],
    "apprentice": ["lesson", "mentor", "study", "practice", "training", "task", "skill", "test"],
    "beggar": ["coin", "food", "shelter", "donation", "companion", "blanket", "corner", "hope"],
    "noble": ["estate", "jewel", "land", "servant", "debt", "banquet", "title", "invitation"],
    "servant": ["errand", "message", "room", "cleaning", "borrow", "task", "tray", "order"],
    "sailor": ["ship", "sea", "map", "storm", "treasure", "harbor", "rope", "voyage"],
    "witch": ["potion", "curse", "herb", "ritual", "secret", "spell", "broom", "charm"],
    "healer": ["medicine", "herb", "remedy", "balm", "potion", "bandage", "patient", "treat"],
    "stable master": ["horse", "saddle", "stable", "hay", "hoof", "stall", "bridle", "groom"],
    "fool": ["joke", "prank", "costume", "festival", "mask", "dance", "jest", "trick"],
    "messenger": ["letter", "message", "news", "parcel", "errand", "route", "delivery", "scroll"],
}

role_with_request_verbs = {
    "farmer": ["plant", "harvest", "plow", "water", "grow", "tend", "sow", "weed"],
    "blacksmith": ["forge", "repair", "sharpen", "melt", "hammer", "craft", "temper", "weld"],
    "merchant": ["trade", "sell", "buy", "bargain", "travel", "import", "export", "haggle"],
    "guard": ["protect", "patrol", "arrest", "escort", "guard", "investigate", "search", "watch"],
    "priest": ["bless", "pray", "preach", "conduct", "heal", "forgive", "guide", "chant"],
    "innkeeper": ["serve", "host", "prepare", "welcome", "clean", "arrange", "cook", "pour"],
    "hunter": ["hunt", "track", "trap", "shoot", "skin", "camp", "ambush", "stalk"],
    "fisherman": ["fish", "cast", "row", "net", "catch", "sail", "bait", "reel"],
    "herbalist": ["gather", "brew", "mix", "identify", "dry", "crush", "prescribe", "grow"],
    "scholar": ["study", "read", "write", "debate", "translate", "teach", "research", "record"],
    "king": ["rule", "decree", "summon", "judge", "command", "host", "lead", "appoint"],
    "queen": ["host", "bless", "support", "arrange", "lead", "visit", "organize", "inspire"],
    "bard": ["sing", "play", "compose", "recite", "entertain", "perform", "dance", "tell"],
    "thief": ["steal", "sneak", "hide", "unlock", "escape", "spy", "pick", "disguise"],
    "knight": ["fight", "defend", "train", "challenge", "escort", "ride", "swear", "compete"],
    "cook": ["cook", "bake", "prepare", "chop", "mix", "season", "taste", "serve"],
    "tailor": ["sew", "cut", "design", "mend", "fit", "embroider", "measure", "stitch"],
    "miner": ["mine", "dig", "extract", "haul", "break", "search", "descend", "explore"],
    "carpenter": ["build", "saw", "hammer", "carve", "repair", "measure", "join", "assemble"],
    "alchemist": ["brew", "distill", "mix", "transmute", "experiment", "analyze", "extract", "infuse"],
    "apprentice": ["learn", "practice", "assist", "observe", "repeat", "help", "study", "train"],
    "beggar": ["beg", "ask", "plead", "wait", "hope", "search", "wander", "appeal"],
    "noble": ["host", "attend", "inherit", "command", "invite", "donate", "invest", "rule"],
    "servant": ["clean", "serve", "deliver", "fetch", "arrange", "assist", "tidy", "prepare"],
    "sailor": ["sail", "navigate", "row", "anchor", "repair", "load", "unload", "explore"],
    "witch": ["curse", "brew", "enchant", "hex", "summon", "mix", "cast", "predict"],
    "healer": ["heal", "treat", "bandage", "diagnose", "prescribe", "soothe", "care", "aid"],
    "stable master": ["feed", "groom", "train", "saddle", "clean", "shoe", "lead", "stable"],
    "fool": ["joke", "prank", "entertain", "mock", "dance", "jest", "tease", "amuse"],
    "messenger": ["deliver", "carry", "run", "announce", "report", "fetch", "travel", "notify"],
}

role_with_request_adjectives = {
    "farmer": ["fertile", "ripe", "fresh", "bountiful", "muddy", "green", "healthy", "abundant"],
    "blacksmith": ["sharp", "sturdy", "heavy", "hot", "strong", "polished", "rusty", "tempered"],
    "merchant": ["valuable", "rare", "exotic", "profitable", "cheap", "expensive", "foreign", "luxurious"],
    "guard": ["safe", "secure", "alert", "loyal", "strict", "brave", "honest", "watchful"],
    "priest": ["holy", "sacred", "faithful", "blessed", "wise", "devout", "pure", "merciful"],
    "innkeeper": ["cozy", "warm", "crowded", "clean", "festive", "welcoming", "busy", "generous"],
    "hunter": ["wild", "stealthy", "skilled", "silent", "quick", "sharp-eyed", "rugged", "patient"],
    "fisherman": ["wet", "salty", "patient", "skilled", "steady", "weathered", "early", "lucky"],
    "herbalist": ["rare", "medicinal", "fragrant", "fresh", "dried", "healing", "bitter", "wild"],
    "scholar": ["ancient", "wise", "curious", "learned", "diligent", "thoughtful", "innovative", "reserved"],
    "king": ["royal", "powerful", "just", "wise", "wealthy", "noble", "commanding", "respected"],
    "queen": ["graceful", "elegant", "kind", "royal", "beautiful", "generous", "noble", "influential"],
    "bard": ["melodic", "witty", "charming", "talented", "creative", "lively", "inspiring", "colorful"],
    "thief": ["sneaky", "quick", "silent", "clever", "shadowy", "nimble", "cunning", "masked"],
    "knight": ["brave", "honorable", "strong", "loyal", "valiant", "armored", "fearless", "noble"],
    "cook": ["delicious", "fresh", "spicy", "sweet", "savory", "hot", "crispy", "tasty"],
    "tailor": ["fashionable", "elegant", "colorful", "fine", "soft", "fitted", "embroidered", "stylish"],
    "miner": ["dusty", "deep", "dark", "rocky", "dangerous", "tough", "gritty", "hidden"],
    "carpenter": ["sturdy", "smooth", "polished", "solid", "well-made", "wooden", "handcrafted", "reliable"],
    "alchemist": ["mysterious", "volatile", "rare", "potent", "colorful", "bubbling", "strange", "magical"],
    "apprentice": ["eager", "young", "inexperienced", "hopeful", "diligent", "curious", "nervous", "ambitious"],
    "beggar": ["hungry", "poor", "cold", "tired", "dirty", "lonely", "needy", "grateful"],
    "noble": ["wealthy", "influential", "arrogant", "generous", "proud", "refined", "dignified", "powerful"],
    "servant": ["obedient", "busy", "helpful", "quiet", "loyal", "tired", "humble", "efficient"],
    "sailor": ["salty", "brave", "weathered", "adventurous", "strong", "rowdy", "restless", "skilled"],
    "witch": ["mysterious", "dark", "wise", "strange", "ancient", "secretive", "powerful", "cunning"],
    "healer": ["gentle", "skilled", "caring", "wise", "compassionate", "patient", "kind", "dedicated"],
    "stable master": ["experienced", "patient", "strong", "gentle", "skilled", "careful", "reliable", "tidy"],
    "fool": ["funny", "silly", "colorful", "loud", "playful", "witty", "clumsy", "cheerful"],
    "messenger": ["swift", "reliable", "discreet", "quick", "tireless", "trusted", "urgent", "punctual"],
}

role_with_request_conditions = {
    "farmer": ["in the morning", "before rain", "during harvest", "at the field", "after sunrise"],
    "blacksmith": ["in the forge", "before noon", "after battle", "during festival", "at the market"],
    "merchant": ["at the market", "during festival", "before sunset", "on the road", "in the city"],
    "guard": ["at night", "during patrol", "at the gate", "after curfew", "in the city"],
    "priest": ["in the temple", "during ceremony", "at dawn", "on holy day", "after prayer"],
    "innkeeper": ["in the evening", "during feast", "at the inn", "before festival", "after sunset"],
    "hunter": ["in the forest", "at dawn", "during hunt", "after rain", "before sunset"],
    "fisherman": ["at the river", "in the morning", "before storm", "during fishing", "on the boat"],
    "herbalist": ["in the woods", "after rain", "at sunrise", "during spring", "in the garden"],
    "scholar": ["in the library", "at night", "during study", "before exam", "after lecture"],
    "king": ["in the throne room", "during council", "at festival", "after victory", "in the morning"],
    "queen": ["in the garden", "during parade", "at the palace", "before ceremony", "after tea"],
    "bard": ["at the tavern", "during festival", "in the evening", "on stage", "after dinner"],
    "thief": ["at night", "in the alley", "during festival", "after curfew", "before dawn"],
    "knight": ["at the castle", "during tournament", "after battle", "on patrol", "before dawn"],
    "cook": ["in the kitchen", "before feast", "during festival", "at noon", "after market"],
    "tailor": ["in the shop", "before festival", "during fitting", "at noon", "after delivery"],
    "miner": ["in the mine", "at dawn", "during shift", "after cave-in", "before sunset"],
    "carpenter": ["at the workshop", "during construction", "before rain", "after delivery", "at noon"],
    "alchemist": ["in the lab", "during experiment", "at midnight", "before sunrise", "after market"],
    "apprentice": ["in the morning", "during lesson", "after mistake", "before exam", "at the workshop"],
    "beggar": ["at the square", "during festival", "in the evening", "after rain", "before meal"],
    "noble": ["at the estate", "during banquet", "before council", "after ceremony", "in the city"],
    "servant": ["in the hall", "during event", "before dinner", "after cleaning", "at the manor"],
    "sailor": ["on the ship", "during storm", "at the harbor", "before voyage", "after docking"],
    "witch": ["in the woods", "at midnight", "during ritual", "before dawn", "after storm"],
    "healer": ["in the clinic", "during epidemic", "at dawn", "after battle", "before sunset"],
    "stable master": ["in the stable", "at dawn", "before race", "after feeding", "during rain"],
    "fool": ["at the festival", "during parade", "in the square", "after joke", "before sunset"],
    "messenger": ["on the road", "during rain", "at dawn", "after delivery", "before sunset"],
}